# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b3a291ee42402508c4e6e7ff0921251ddfddcd84f6480a277a0ca40d2b53a8967a8c7c409d0c9d7b57b52df8830378b5cee691a501814dcde85852227667856d

test:
  secret_key_base: 7bb131e9fd94a7ecd242746b7309448bde0c28e6a9ab5c4d0d281f4895e99b703d8b2ad385f3ffc9ff931fd0a12024297a9fd60056eab2217dc99dedd10bc112

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
